logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# Spring Actuators Properties    
endpoints: 
  beans: 
    sensitive: false
  shutdown: 
    enabled: true
    sensitive: false
