spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campaignmgmt
    username: banyan
    password: banyancampaign
    testOnBorrow: true
    validationQuery: SELECT 1   

    
# HTTP Server
server:
  port: 2226   # HTTP (Tomcat) port
  
# Spring Actuators Properties       
management: 
  port: 2326
