spring:
  data: 
    mongodb: 
      host: 10.0.1.151
      database: ContentServices
      port: 27017
    
# HTTP Server
server:
  port: 2221   # HTTP (Tomcat) port
  host: 52.66.89.202
  
# Spring Actuators Properties     
management: 
  port: 2321
  address: 127.0.0.1
  
##  ffmpeg Path set up
ffmpegexePath: /usr/bin/ffmpeg311/ffmpeg
qtfaststartPath: /usr/bin/ffmpeg311/qt-faststart
ffprobeexePath: /usr/bin/ffmpeg311/ffprobe
  