spring:
  data: 
    mongodb: 
      host: localhost
      database: LocationServices
      port: 27017
    
# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port
  
# Spring Actuators Properties     
management: 
  port: 2323
